services:
  - type: web
    name: outertiers-api
    env: node
    buildCommand: npm install -g pnpm@8 && pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: WEBSITE_API_SECRET
        sync: false
