services:
  - type: web
    name: outertiers-api
    env: node
    buildCommand: npm install -g pnpm@8 && pnpm install
    startCommand: pnpm exec tsx src/index.ts
    envVars:
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
      - key: DATABASE_URL
        sync: false
      - key: WEBSITE_API_SECRET
        sync: false

